# site name
prefixName: cupid
siteName: 土豆&登哥
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: # https://sakura.hojun.cn
description: Live your life with passion! With some drive!
cdn:  https://cdn.jsdelivr.net/gh/beaexecutive/CDN@1.0
pjax: 1
# 1开启
mathjax: 0

notice: # hexo-Sakura主题已经开源，目前正在开发中...
lazyloadImg: # https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: {
    技术: {path: javascript:;, fa: fa-code },
    生活: {path: javascript:;, fa: fa-file-text-o },
    资源: {path: javascript:;, fa: fa-cloud-download },
    随想: {path: javascript:;, fa: fa-commenting-o },
    转载: {path: javascript:;, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    书单: {path: javascript:;, fa: fa-th-list faa-bounce },
    番组: {path: javascript:;, fa: fa-film faa-vertical },
    歌单: {path: javascript:;, fa: fa-headphones },
    图集: {path: javascript:;, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: javascript:;, fa: fa-link faa-shake }
  赞赏: { path: javascript:;, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench }
  客户端: { path: javascript:;, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - images/cover/(1).jpg.webp
  - images/cover/(2).jpg.webp
  - images/cover/(3).jpg.webp
  - images/cover/(4).jpg.webp
  - images/cover/(5).jpg.webp
  - images/cover/(6).jpg.webp
  - images/cover/(7).jpg.webp
  - images/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
#startdash:
#  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
#  - {url: http://space.bilibili.com, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
#  - {url: /, title: beaexecutive的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 12/18/2020

#social  url, img PC端配置
social:
#  github: {url: /#, img: /img/social/github.png}
#  sina: {url: /#, img: /img/social/sina.png}
#  wangyiyun: {url: /#, img: /img/social/wangyiyun.png}
#  zhihu: {url: /#, img: /img/social/zhihu.png}
#  email: {url: /#, img: /img/social/email.svg}
#  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
#  wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

  github: {url: http://github.com/, img: /img/social/github.png}
  sina: {url: http://weibo.com/, img: /img/social/sina.png}
  wangyiyun: {url: http://weibo.com/, img: /img/social/wangyiyun.png}
  zhihu: {url: http://weibo.com/, img: /img/social/zhihu.png}
  email: {url: http://weibo.com, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com, fa: fa-qq, color: 25c6fe}

#donate:
##  paypal: https://www.paypal.me/hojuncn
##  alipay: /img/custom/donate/AliPayQR.jpg
##  wechat: /img/custom/donate/WeChanQR.jpg
##  wechatSQ: /img/custom/donate/WeChanSQ.jpg
#  paypal:
#  alipay:
#  wechat:
#  wechatSQ:

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
#  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  url:
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer:
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId:
v_appKey:

